jobs:
- job: infrastructure
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: 'src'
      zipAfterPublish: false
      modifyOutputPath: false
    displayName: 'Build and publish ASP.NET Core app'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'infra'  
    displayName: 'NPM install packages'
  - task: Pulumi@0
    inputs:
      azureSubscription: 'Microsoft Azure Sponsorship(ebca75f3-9e5e-4a96-a777-aeeb2777dbde)'
      command: 'up'
      args: '--yes'
      cwd: 'infra'
      stack: 'dev'
    displayName: 'Install pulumi and run infra code'
    name: pulumi
    env:
      PULUMI_ACCESS_TOKEN: $(pulumi.access.token)